-- AVTOMATIK YARATILGAN FAYL — tahrirlamang. Manba: scripts/question-bank.mjs
-- Yaratish: npm run seed:sql
-- Savollar soni: 120

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kompyuter qurilmalari va dasturiy taʼminot', 'easy', 'single_choice', 'Kompyuterning qoʻl bilan ushlash mumkin boʻlgan fizik qismlari qanday ataladi?', '["Dasturiy taʼminot (software)","Drayver","Operatsion tizim","Apparat taʼminoti (hardware)"]'::jsonb, '3'::jsonb, 'Apparat taʼminoti — kompyuterning fizik qismlari: korpus, monitor, klaviatura, protsessor va boshqalar.', 'Bu qismlarni koʻrish va ushlash mumkin.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Kompyuterning qoʻl bilan ushlash mumkin boʻlgan fizik qismlari qanday ataladi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kompyuter qurilmalari va dasturiy taʼminot', 'easy', 'single_choice', 'Quyidagilardan qaysi biri amaliy dasturiy taʼminotga misol boʻladi?', '["Kompyuterni yuklovchi dastur (BIOS)","Qurilma drayveri","Operatsion tizim","Matn muharriri"]'::jsonb, '3'::jsonb, 'Amaliy dasturlar foydalanuvchiga aniq vazifani bajarishda yordam beradi: matn yozish, jadval tuzish, rasm chizish.', 'Foydalanuvchi oʻz ishini bajarish uchun ishlatadigan dasturni toping.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Quyidagilardan qaysi biri amaliy dasturiy taʼminotga misol boʻladi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kompyuter qurilmalari va dasturiy taʼminot', 'medium', 'single_choice', 'Tizim dasturiy taʼminotining asosiy vazifasi nima?', '["Faqat kompyuter oʻyinlarini ishga tushirish","Kompyuter apparatini boshqarish va boshqa dasturlar ishlashi uchun muhit yaratish","Hujjatlarni chiroyli bezash","Internetdan rasmlarni yuklab olish"]'::jsonb, '1'::jsonb, 'Tizim dasturlari (operatsion tizim, drayverlar, utilitalar) apparatni boshqaradi va amaliy dasturlarga xizmat qiladi.', 'Operatsion tizim ham shu guruhga kiradi.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Tizim dasturiy taʼminotining asosiy vazifasi nima?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kompyuter qurilmalari va dasturiy taʼminot', 'easy', 'true_false', 'Drayver — bu qurilma bilan operatsion tizim oʻrtasida aloqa oʻrnatadigan dastur.', '["Toʻgʻri","Notoʻgʻri"]'::jsonb, '0'::jsonb, 'Toʻgʻri. Drayver operatsion tizimga printer, skaner kabi qurilmani qanday boshqarishni “tushuntiradi”.', 'Yangi printer ulanganda kompyuter nimani oʻrnatadi?', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Drayver — bu qurilma bilan operatsion tizim oʻrtasida aloqa oʻrnatadigan dastur.' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kompyuter qurilmalari va dasturiy taʼminot', 'medium', 'single_choice', 'Mikrofondan kelgan analog ovoz signalini kompyuter qayta ishlashi uchun u qanday shaklga oʻtkazilishi kerak?', '["Mexanik shaklga","Optik shaklga","Hech qanday oʻzgartirish kerak emas","Raqamli (ikkilik) shaklga"]'::jsonb, '3'::jsonb, 'Kompyuter faqat raqamli (0 va 1) maʼlumot bilan ishlaydi. Analog-raqamli oʻzgartirgich (ADC) signalni raqamliga aylantiradi.', 'Kompyuter faqat 0 va 1 ni tushunadi.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Mikrofondan kelgan analog ovoz signalini kompyuter qayta ishlashi uchun u qanday shaklga oʻtkazilishi kerak?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kompyuter tizimining asosiy komponentlari', 'easy', 'single_choice', 'Kompyuterning “miyasi” deb ataladigan, buyruqlarni bajaradigan qismi qaysi?', '["Markaziy protsessor (CPU)","Qattiq disk","Monitor","Klaviatura"]'::jsonb, '0'::jsonb, 'Markaziy protsessor dastur buyruqlarini bajaradi va hisob-kitoblarni amalga oshiradi.', 'Uning qisqartmasi uch harfdan iborat.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Kompyuterning “miyasi” deb ataladigan, buyruqlarni bajaradigan qismi qaysi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kompyuter tizimining asosiy komponentlari', 'easy', 'single_choice', 'Kompyuter oʻchirilganda operativ xotira (RAM)dagi maʼlumotlar bilan nima sodir boʻladi?', '["Avtomatik ravishda ROMga koʻchadi","Toʻliq saqlanib qoladi","Oʻchib ketadi","Internetga yuboriladi"]'::jsonb, '2'::jsonb, 'RAM — energiyaga bogʻliq (volatile) xotira: elektr oʻchishi bilan undagi maʼlumot yoʻqoladi.', 'Shuning uchun hujjatni oʻchirishdan oldin saqlash kerak.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Kompyuter oʻchirilganda operativ xotira (RAM)dagi maʼlumotlar bilan nima sodir boʻladi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kompyuter tizimining asosiy komponentlari', 'medium', 'single_choice', 'ROM xotirasining asosiy xususiyati qaysi?', '["Faqat videofayllarni saqlaydi","Elektr oʻchishi bilan tozalanadi","Foydalanuvchi har kuni unga oʻyin yozadi","Asosan oʻqish uchun moʻljallangan va elektr oʻchganda ham maʼlumot saqlanadi"]'::jsonb, '3'::jsonb, 'ROM (Read Only Memory) — doimiy xotira. Unda kompyuterni ishga tushirish dasturi (BIOS/UEFI) saqlanadi.', 'Read Only Memory — “faqat oʻqish uchun xotira”.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'ROM xotirasining asosiy xususiyati qaysi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kompyuter tizimining asosiy komponentlari', 'medium', 'single_choice', 'Kompyuter yoqilganda uni ishga tushirish (boot) koʻrsatmalari odatda qayerda saqlanadi?', '["ROM xotirada","RAM xotirada","Sichqonchada","Monitorda"]'::jsonb, '0'::jsonb, 'Yuklovchi koʻrsatmalar ROMda saqlanadi, chunki ular elektr oʻchganda ham yoʻqolmasligi kerak.', 'Bu xotira elektr oʻchganda ham maʼlumotni yoʻqotmaydi.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Kompyuter yoqilganda uni ishga tushirish (boot) koʻrsatmalari odatda qayerda saqlanadi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kompyuter tizimining asosiy komponentlari', 'medium', 'single_choice', 'Quyidagilardan qaysi biri kompyuterning ICHKI xotirasiga kiradi?', '["USB fleshka","DVD disk","RAM va ROM","Tashqi qattiq disk"]'::jsonb, '2'::jsonb, 'Ichki (asosiy) xotira — protsessor bevosita foydalanadigan RAM va ROM. Qolganlari tashqi (yordamchi) xotira.', 'Ular ona platada joylashgan.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Quyidagilardan qaysi biri kompyuterning ICHKI xotirasiga kiradi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kompyuter tizimining asosiy komponentlari', 'easy', 'single_choice', 'Tashqi (yordamchi) xotira qurilmalarining asosiy vazifasi nima?', '["Tasvirni ekranda koʻrsatish","Ovozni yozib olish","Dastur buyruqlarini bajarish","Maʼlumotlarni uzoq muddat saqlash"]'::jsonb, '3'::jsonb, 'Qattiq disk, SSD, fleshka kabi qurilmalar maʼlumotni elektr oʻchganda ham uzoq muddat saqlaydi.', 'Fayllaringiz kompyuter oʻchganda qayerda qoladi?', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Tashqi (yordamchi) xotira qurilmalarining asosiy vazifasi nima?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Operatsion tizimlar', 'easy', 'single_choice', 'Quyidagilardan qaysi biri operatsion tizim?', '["Linux","Paint","Microsoft Word","Google Chrome"]'::jsonb, '0'::jsonb, 'Linux — operatsion tizim. Qolganlari operatsion tizim ichida ishlaydigan amaliy dasturlar.', 'Uning ramzi — pingvin.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Quyidagilardan qaysi biri operatsion tizim?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Operatsion tizimlar', 'easy', 'single_choice', 'GUI qisqartmasi nimani anglatadi?', '["Grafik foydalanuvchi interfeysi","Buyruqlar satri interfeysi","Global foydalanuvchi interneti","Grafik ulanish indeksi"]'::jsonb, '0'::jsonb, 'GUI (Graphical User Interface) — oynalar, belgilar (ikonkalar) va menyular orqali boshqariladigan interfeys.', 'G — Graphical.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'GUI qisqartmasi nimani anglatadi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Operatsion tizimlar', 'medium', 'single_choice', 'Buyruqlar satri interfeysi (CLI)ning GUIga nisbatan afzalligi qaysi?', '["Yangi boshlovchilar uchun oʻrganish juda oson","Tajribali foydalanuvchiga tizimni toʻliqroq va tezroq boshqarish imkonini beradi","Buyruqlarni yodlash umuman shart emas","Faqat sichqoncha bilan boshqariladi"]'::jsonb, '1'::jsonb, 'CLIda buyruqlar yoziladi: u kam resurs talab qiladi va mutaxassisga koʻproq imkoniyat beradi, lekin buyruqlarni bilish kerak.', 'Bu interfeysdan koʻpincha tizim administratorlari foydalanadi.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Buyruqlar satri interfeysi (CLI)ning GUIga nisbatan afzalligi qaysi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Operatsion tizimlar', 'hard', 'single_choice', 'WIMP interfeysi qaysi elementlardan iborat?', '["Soʻz, rasm, musiqa, foto","Wi-Fi, kiritish, xotira, protsessor","Veb, internet, pochta, printer","Oynalar, belgilar (ikonkalar), menyular, koʻrsatkich"]'::jsonb, '3'::jsonb, 'WIMP — Windows, Icons, Menus, Pointer. Bu grafik interfeysning klassik koʻrinishi.', 'W — Windows, P — Pointer.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'WIMP interfeysi qaysi elementlardan iborat?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Operatsion tizimlar', 'easy', 'true_false', 'Operatsion tizim xotirani, fayllarni va ulangan qurilmalarni boshqaradi.', '["Toʻgʻri","Notoʻgʻri"]'::jsonb, '0'::jsonb, 'Toʻgʻri. Bular operatsion tizimning asosiy vazifalari.', 'Operatsion tizim — kompyuterning “boshqaruvchisi”.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Operatsion tizim xotirani, fayllarni va ulangan qurilmalarni boshqaradi.' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kompyuter turlari', 'medium', 'single_choice', 'Mainframe kompyuterlar asosan qayerda ishlatiladi?', '["Fleshkada fayl saqlashda","Banklar va yirik tashkilotlarda juda koʻp tranzaksiyalarni qayta ishlashda","Uyda kompyuter oʻyinlari oʻynashda","Qoʻl soatida qadamlarni sanashda"]'::jsonb, '1'::jsonb, 'Mainframe — bir vaqtda minglab foydalanuvchi va tranzaksiyalarga xizmat qiladigan kuchli kompyuter.', 'Bank kartangiz bilan toʻlov qilganingizda shunday tizim ishlaydi.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Mainframe kompyuterlar asosan qayerda ishlatiladi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kompyuter turlari', 'easy', 'single_choice', 'Noutbukning stol kompyuteriga nisbatan asosiy afzalligi qaysi?', '["Qismlarini almashtirish osonroq","Elektr energiyasini koʻproq sarflaydi","Har doim kuchliroq","Koʻchma — uni osongina olib yurish mumkin"]'::jsonb, '3'::jsonb, 'Noutbukda batareya, ekran va klaviatura bitta korpusda — uni istalgan joyga olib borish mumkin.', 'Uni sumkada olib yurish mumkin.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Noutbukning stol kompyuteriga nisbatan asosiy afzalligi qaysi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kompyuter turlari', 'medium', 'single_choice', 'Stol kompyuterining (desktop) noutbukka nisbatan afzalligi qaysi?', '["Unda doim sensorli ekran boʻladi","Qismlarini almashtirish va kengaytirish osonroq","Batareyada uzoq ishlaydi","Choʻntakka sigʻadi"]'::jsonb, '1'::jsonb, 'Stol kompyuterining korpusi katta, shuning uchun xotira, videokarta kabi qismlarni oson almashtirish mumkin; u yaxshiroq sovutiladi.', 'Korpusi katta va ochiladi.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Stol kompyuterining (desktop) noutbukka nisbatan afzalligi qaysi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kompyuter turlari', 'easy', 'single_choice', 'Smart soat qaysi kompyuter turiga kiradi?', '["Taqiladigan qurilma (wearable)","Mainframe","Superkompyuter","Stol kompyuteri"]'::jsonb, '0'::jsonb, 'Smart soat — tanaga taqiladigan kichik kompyuter: puls, qadamlar va xabarlarni kuzatadi.', 'Uni qoʻlga taqib yurish mumkin.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Smart soat qaysi kompyuter turiga kiradi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Yangi texnologiyalarning taʼsiri', 'easy', 'single_choice', 'Sunʼiy intellekt (AI) deganda nima tushuniladi?', '["Faqat juda tez ishlaydigan protsessor","Qogʻozga chop etishning yangi usuli","Internet tezligining oʻlchov birligi","Inson tafakkuriga oʻxshab oʻrganadigan va qaror qabul qiladigan kompyuter tizimlari"]'::jsonb, '3'::jsonb, 'Sunʼiy intellekt — nutqni tanish, tasvirni aniqlash, tarjima qilish kabi “aqlli” vazifalarni bajaradigan tizimlar.', 'Ovozli yordamchilar va tarjimonlar shunga misol.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Sunʼiy intellekt (AI) deganda nima tushuniladi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Yangi texnologiyalarning taʼsiri', 'medium', 'single_choice', 'Qaysi texnologiya real dunyo tasviri ustiga virtual obyektlarni qoʻshib koʻrsatadi?', '["Bluetooth","Bulutli saqlash","Kengaytirilgan reallik (AR)","Virtual reallik (VR)"]'::jsonb, '2'::jsonb, 'AR real muhitni saqlab, ustiga raqamli obyektlar qoʻshadi. VR esa foydalanuvchini butunlay virtual dunyoga olib kiradi.', 'Telefon kamerasida real xona koʻrinadi, ustida esa virtual mebel paydo boʻladi.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Qaysi texnologiya real dunyo tasviri ustiga virtual obyektlarni qoʻshib koʻrsatadi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Yangi texnologiyalarning taʼsiri', 'medium', 'single_choice', 'Robotlarning ishlab chiqarishdagi afzalligi qaysi?', '["Hech qachon taʼmir talab qilmaydi","Har qanday kutilmagan vaziyatda inson kabi qaror qabul qiladi","Ularni oʻrnatish hech qanday xarajat talab qilmaydi","Charchamasdan, bir xil aniqlikda uzoq ishlay oladi"]'::jsonb, '3'::jsonb, 'Robotlar takroriy ishlarni yuqori aniqlikda bajaradi, lekin ular qimmat va texnik xizmat talab qiladi.', 'Robot dam olishga muhtoj emas.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Robotlarning ishlab chiqarishdagi afzalligi qaysi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Yangi texnologiyalarning taʼsiri', 'hard', 'single_choice', 'Avtonom (oʻzi boshqariladigan) avtomobillarning kamchiliklaridan biri qaysi?', '["Ular faqat kechasi harakatlana oladi","Ular hech qanday sensor ishlatmaydi","Sensor yoki dasturiy xatolik baxtsiz hodisaga olib kelishi mumkin","Ular umuman energiya sarflamaydi"]'::jsonb, '2'::jsonb, 'Avtonom avtomobillar sensorlar va dasturga tayanadi: ulardagi nosozlik xavfli boʻlishi mumkin, xakerlik hujumi xavfi ham bor.', 'Kamera yoki radar xato qilsa nima boʻladi?', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Avtonom (oʻzi boshqariladigan) avtomobillarning kamchiliklaridan biri qaysi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kiritish qurilmalari', 'easy', 'single_choice', 'Quyidagilardan qaysi biri kiritish qurilmasi?', '["Monitor","Printer","Karnay","Mikrofon"]'::jsonb, '3'::jsonb, 'Mikrofon ovozni kompyuterga kiritadi. Monitor, printer va karnay — chiqarish qurilmalari.', 'U ovozni “tinglaydi”.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Quyidagilardan qaysi biri kiritish qurilmasi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kiritish qurilmalari', 'medium', 'single_choice', 'Grafik planshet asosan kimlar uchun qulay?', '["Ovoz yozuvchi musiqachilar","Faqat buxgalterlar","Server administratorlari","Rassom va dizaynerlar"]'::jsonb, '3'::jsonb, 'Grafik planshetda maxsus qalam bilan chizish mumkin — bu qoʻl harakatini aniq kiritadi.', 'Unda qalam bilan chiziladi.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Grafik planshet asosan kimlar uchun qulay?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kiritish qurilmalari', 'medium', 'single_choice', 'Sensorli ekran qanday qurilma hisoblanadi?', '["Ham kiritish, ham chiqarish qurilmasi","Faqat chiqarish qurilmasi","Saqlash qurilmasi","Faqat kiritish qurilmasi"]'::jsonb, '0'::jsonb, 'Sensorli ekran barmoq teginishini qabul qiladi (kiritish) va tasvirni koʻrsatadi (chiqarish).', 'U ham koʻrsatadi, ham teginishni sezadi.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Sensorli ekran qanday qurilma hisoblanadi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kiritish qurilmalari', 'easy', 'single_choice', 'Raqamli fotokamera kompyuterga nimani kiritadi?', '["Faqat matnni","Tasvir va videoni","Faqat ovozni","Elektr energiyasini"]'::jsonb, '1'::jsonb, 'Raqamli kamera tasvirni raqamli faylga aylantiradi va uni kompyuterga uzatish mumkin.', 'U suratga oladi.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Raqamli fotokamera kompyuterga nimani kiritadi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Maʼlumotlarni bevosita kiritish qurilmalari', 'medium', 'single_choice', 'Test javob varaqalaridagi qora qilib boʻyalgan kataklarni oʻqiydigan texnologiya qaysi?', '["RFID (radiochastotali identifikatsiya)","MICR (magnit siyohni oʻqish)","OMR (optik belgilarni oʻqish)","OCR (optik belgilarni tanish)"]'::jsonb, '2'::jsonb, 'OMR qogʻozdagi belgilangan joylarni (kataklarni) aniqlaydi. Test va soʻrovnomalarni tez tekshirishda ishlatiladi.', 'Bu texnologiya harflarni emas, belgilangan kataklarni oʻqiydi.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Test javob varaqalaridagi qora qilib boʻyalgan kataklarni oʻqiydigan texnologiya qaysi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Maʼlumotlarni bevosita kiritish qurilmalari', 'hard', 'single_choice', 'Bank cheklaridagi maxsus magnit siyoh bilan yozilgan raqamlarni oʻqiydigan texnologiya qaysi?', '["QR kod","MICR","Bluetooth","OMR"]'::jsonb, '1'::jsonb, 'MICR (Magnetic Ink Character Recognition) magnit siyohli belgilarni oʻqiydi; ular ustiga yozilsa ham oʻqiladi.', 'Qisqartmadagi M — Magnetic.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Bank cheklaridagi maxsus magnit siyoh bilan yozilgan raqamlarni oʻqiydigan texnologiya qaysi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Maʼlumotlarni bevosita kiritish qurilmalari', 'medium', 'single_choice', 'Bosma matnli qogʻozni skanerlab, uni tahrirlanadigan matnga aylantiruvchi texnologiya qaysi?', '["GPS","OMR","RFID","OCR"]'::jsonb, '3'::jsonb, 'OCR (Optical Character Recognition) skanerlangan tasvirdagi harflarni taniydi va matn fayliga aylantiradi.', 'C — Character, yaʼni “belgi/harf”.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Bosma matnli qogʻozni skanerlab, uni tahrirlanadigan matnga aylantiruvchi texnologiya qaysi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Maʼlumotlarni bevosita kiritish qurilmalari', 'medium', 'single_choice', 'Kontaktsiz toʻlov kartalari va tovar yorliqlarini masofadan radiotoʻlqin orqali oʻqiydigan texnologiya qaysi?', '["OMR","RFID / NFC","Matritsali printer","MICR"]'::jsonb, '1'::jsonb, 'RFID radiotoʻlqinlar orqali chipdagi maʼlumotni oʻqiydi. NFC — uning juda qisqa masofali turi (kontaktsiz toʻlov).', 'Kartani terminalga tekkizish shart emas, yaqinlashtirish kifoya.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Kontaktsiz toʻlov kartalari va tovar yorliqlarini masofadan radiotoʻlqin orqali oʻqiydigan texnologiya qaysi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Maʼlumotlarni bevosita kiritish qurilmalari', 'easy', 'single_choice', 'Shtrix-kod oʻquvchi asosan qayerda ishlatiladi?', '["Musiqa tinglashda","Rasm chizishda","Doʻkon kassalarida tovarlarni aniqlashda","Ovoz yozishda"]'::jsonb, '2'::jsonb, 'Shtrix-kod oʻquvchi tovar kodini bir zumda oʻqiydi, kompyuter esa narxini topadi.', 'Tovarlardagi qora-oq chiziqlarni eslang.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Shtrix-kod oʻquvchi asosan qayerda ishlatiladi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Chiqarish qurilmalari', 'easy', 'single_choice', 'Quyidagilardan qaysi biri chiqarish qurilmasi?', '["Mikrofon","Skaner","Klaviatura","Printer"]'::jsonb, '3'::jsonb, 'Printer kompyuterdagi maʼlumotni qogʻozga chiqaradi. Qolganlari kiritish qurilmalari.', 'U qogʻozga chop etadi.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Quyidagilardan qaysi biri chiqarish qurilmasi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Chiqarish qurilmalari', 'medium', 'single_choice', 'Koʻp sahifali hujjatlarni tez va sifatli chop etish uchun qaysi printer eng mos?', '["Plotter","Lazerli printer","3D printer","Matritsali printer"]'::jsonb, '1'::jsonb, 'Lazerli printer tez ishlaydi, sifati yuqori va katta hajmdagi hujjatlar uchun tejamkor.', 'Ofislarda eng koʻp uchraydigan printer.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Koʻp sahifali hujjatlarni tez va sifatli chop etish uchun qaysi printer eng mos?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Chiqarish qurilmalari', 'hard', 'single_choice', 'Matritsali (nuqtali) printer hozir ham ishlatilishining sababi nima?', '["U eng sokin ishlaydigan printer","U zarb bilan chop etadi va koʻp qatlamli (kopirkali) blankalarni bir yoʻla toʻldira oladi","U uch oʻlchamli obyektlar yasaydi","U rangli fotosuratlarni eng sifatli chiqaradi"]'::jsonb, '1'::jsonb, 'Matritsali printer igna bilan lenta orqali urib chop etadi: shovqinli, lekin koʻp nusxali blankalar uchun qulay va chidamli.', 'U lentaga igna bilan uradi.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Matritsali (nuqtali) printer hozir ham ishlatilishining sababi nima?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Chiqarish qurilmalari', 'medium', 'single_choice', '3D printer nima qiladi?', '["Material qatlamlarini ketma-ket qoʻyib uch oʻlchamli obyekt yasaydi","Qogʻozga uch xil rangda chop etadi","Ovozni uch kanalda chiqaradi","Uch oʻlchamli tasvirni skanerlaydi"]'::jsonb, '0'::jsonb, '3D printer plastik yoki boshqa materialni qatlamma-qatlam qoʻyib, raqamli modeldan real buyum yasaydi.', 'Natijani qoʻlga olib ushlash mumkin.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = '3D printer nima qiladi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Chiqarish qurilmalari', 'hard', 'single_choice', 'Aktuator (ijro mexanizmi) qanday qurilma?', '["Kompyuter signaliga koʻra harakat hosil qiluvchi chiqarish qurilmasi (masalan, motor yoki klapan)","Maʼlumot saqlaydigan disk","Tarmoq kabeli","Haroratni oʻlchaydigan sensor"]'::jsonb, '0'::jsonb, 'Aktuatorlar boshqaruv tizimlarida ishlatiladi: kompyuter buyrugʻi bilan eshikni ochadi, motorni aylantiradi, klapanni yopadi.', 'U “harakat” qiladi.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Aktuator (ijro mexanizmi) qanday qurilma?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Saqlash qurilmalari va maʼlumot almashish', 'medium', 'single_choice', 'Qaysi saqlash qurilmasida maʼlumot aylanuvchi magnitlangan disklarda saqlanadi?', '["SSD","USB fleshka","Blu-ray disk","HDD (qattiq disk)"]'::jsonb, '3'::jsonb, 'HDD ichida aylanuvchi magnit plastinalar va oʻqish-yozish kallagi bor.', 'Bu qurilma ichida tez aylanadigan plastinalar bor.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Qaysi saqlash qurilmasida maʼlumot aylanuvchi magnitlangan disklarda saqlanadi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Saqlash qurilmalari va maʼlumot almashish', 'medium', 'single_choice', 'Quyidagi optik disklardan qaysi biri eng katta sigʻimga ega?', '["Barchasining sigʻimi bir xil","Blu-ray","CD","DVD"]'::jsonb, '1'::jsonb, 'Odatda: CD ≈ 700 MB, DVD ≈ 4,7 GB, Blu-ray ≈ 25 GB (bir qatlamli).', 'Uning nomida “koʻk nur” bor.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Quyidagi optik disklardan qaysi biri eng katta sigʻimga ega?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Saqlash qurilmalari va maʼlumot almashish', 'easy', 'single_choice', 'Optik disklardan maʼlumot qanday oʻqiladi?', '["Lazer nuri yordamida","Elektr zaryadi bilan","Magnit kallak bilan","Radiotoʻlqin bilan"]'::jsonb, '0'::jsonb, 'Optik diskovod lazer nurini disk sirtiga yoʻnaltiradi va qaytgan nurdan maʼlumotni oʻqiydi.', '“Optik” soʻzi yorugʻlik bilan bogʻliq.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Optik disklardan maʼlumot qanday oʻqiladi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Saqlash qurilmalari va maʼlumot almashish', 'medium', 'single_choice', 'SSD maʼlumotni qanday saqlaydi?', '["Aylanuvchi magnit disklarda","Flesh-xotira mikrosxemalarida, harakatlanuvchi qismlarsiz","Magnit lentada","Lazer bilan yoziladigan diskda"]'::jsonb, '1'::jsonb, 'SSD — qattiq jismli (solid state) xotira: unda mexanik qismlar yoʻq, shuning uchun u tez va zarbaga chidamli.', 'Solid State — “qattiq jismli”.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'SSD maʼlumotni qanday saqlaydi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Saqlash qurilmalari va maʼlumot almashish', 'easy', 'single_choice', 'Bulutli saqlash (cloud storage) nima?', '["Ob-havo maʼlumotlarini saqlash","Maʼlumotlarni internet orqali uzoqdagi serverlarda saqlash","Maʼlumotlarni faqat fleshkada saqlash","Kompyuterning operativ xotirasi"]'::jsonb, '1'::jsonb, 'Bulutli xizmatlarda fayllar provayder serverlarida saqlanadi va ularga istalgan qurilmadan internet orqali kirish mumkin.', 'Fayllarga internet orqali istalgan joydan kirish mumkin.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Bulutli saqlash (cloud storage) nima?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Saqlash qurilmalarining afzallik va kamchiliklari', 'medium', 'single_choice', 'SSDning HDDga nisbatan afzalligi qaysi?', '["Tezroq ishlaydi va zarbaga chidamliroq","Faqat bir marta yoziladi","Sigʻimi har doim kattaroq","Har doim arzonroq"]'::jsonb, '0'::jsonb, 'SSDda harakatlanuvchi qismlar yoʻq: u tezroq, sokinroq va zarbaga chidamli. Lekin bir gigabayt hajmi odatda HDDdan qimmatroq.', 'Unda aylanadigan qismlar yoʻq.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'SSDning HDDga nisbatan afzalligi qaysi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Saqlash qurilmalarining afzallik va kamchiliklari', 'hard', 'single_choice', 'Magnit lentaning afzalligi qaysi?', '["Sensorli boshqaruvga ega","Kerakli faylga bir zumda toʻgʻridan-toʻgʻri kirish","Juda katta hajmdagi maʼlumotni arzon zaxiralash (backup)","Choʻntakda olib yurish uchun eng qulay"]'::jsonb, '2'::jsonb, 'Magnit lenta juda katta sigʻimli va arzon, shuning uchun yirik tashkilotlar undan zaxira nusxalar uchun foydalanadi.', 'Yirik tashkilotlar zaxira nusxalarni unda saqlaydi.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Magnit lentaning afzalligi qaysi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Saqlash qurilmalarining afzallik va kamchiliklari', 'hard', 'single_choice', 'Magnit lentaning asosiy kamchiligi nimada?', '["Maʼlumotga faqat ketma-ket kirish mumkin, shuning uchun kerakli faylni topish sekin","U juda qimmat","U faqat bitta faylni saqlay oladi","Unga maʼlumot yozib boʻlmaydi"]'::jsonb, '0'::jsonb, 'Lentada kerakli joyga yetish uchun undan oldingi qismni “oʻrab oʻtish” kerak — bu ketma-ket (sequential) kirish.', 'Eski audiokassetani eslang.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Magnit lentaning asosiy kamchiligi nimada?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Saqlash qurilmalarining afzallik va kamchiliklari', 'easy', 'single_choice', 'USB fleshkaning afzalligi qaysi?', '["Unga faqat bir marta yozish mumkin","Uni hech qachon yoʻqotib boʻlmaydi","Kichik, yengil, koʻchma va aksariyat kompyuterlarga mos","Sigʻimi har doim qattiq diskdan katta"]'::jsonb, '2'::jsonb, 'Fleshka choʻntakka sigʻadi va USB porti bor deyarli har qanday kompyuterda ishlaydi. Kamchiligi — kichikligi tufayli oson yoʻqoladi.', 'Uni kalitlar bilan birga olib yurish mumkin.', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'USB fleshkaning afzalligi qaysi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Saqlash qurilmalarining afzallik va kamchiliklari', 'medium', 'single_choice', 'Bulutli saqlashning kamchiligi qaysi?', '["Undan faqat bitta qurilmada foydalanish mumkin","Maʼlumot hech qayerda saqlanmaydi","Internet aloqasi boʻlmasa, fayllarga kirish qiyin","U har doim bepul va cheksiz"]'::jsonb, '2'::jsonb, 'Bulutli xotira internetga bogʻliq; maʼlumot xavfsizligi esa provayderga ham bogʻliq boʻladi.', 'Bu xizmatga nima orqali ulanamiz?', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Bulutli saqlashning kamchiligi qaysi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Saqlash qurilmalarining afzallik va kamchiliklari', 'medium', 'single_choice', 'Optik disklarning (CD/DVD) kamchiligi qaysi?', '["Ular magnit maydonidan darrov buziladi","Ularni hech bir kompyuter oʻqiy olmaydi","Tirnalsa, maʼlumot oʻqilmay qolishi mumkin","Ular elektr oʻchganda maʼlumotni yoʻqotadi"]'::jsonb, '2'::jsonb, 'Optik disk sirtidagi tirnalishlar lazer nurini buzadi. Ularning sigʻimi ham zamonaviy qurilmalarga nisbatan kichik.', 'Disk sirtiga nima zarar yetkazadi?', null, 100, 20, 1
where not exists (select 1 from public.questions where question_text = 'Optik disklarning (CD/DVD) kamchiligi qaysi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kiritish qurilmalari', 'easy', 'image_identification', 'Rasmda qanday qurilma tasvirlangan?', '["Skaner","Grafik planshet","Sensorli panel","Klaviatura"]'::jsonb, '3'::jsonb, 'Klaviatura — matn, raqam va buyruqlarni kiritish qurilmasi.', 'Unda harf va raqamli tugmalar bor.', '/assets/devices/keyboard.webp', 150, 25, 2
where not exists (select 1 from public.questions where question_text = 'Rasmda qanday qurilma tasvirlangan?' and image_url is not distinct from '/assets/devices/keyboard.webp');

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kiritish qurilmalari', 'easy', 'image_identification', 'Rasmdagi qurilma qaysi turkumga kiradi?', '["Tarmoq qurilmasi","Chiqarish qurilmasi","Kiritish qurilmasi","Saqlash qurilmasi"]'::jsonb, '2'::jsonb, 'Sichqoncha — koʻrsatkich (kursor)ni boshqaradigan kiritish qurilmasi.', 'U kursorni boshqaradi.', '/assets/devices/mouse.webp', 150, 25, 2
where not exists (select 1 from public.questions where question_text = 'Rasmdagi qurilma qaysi turkumga kiradi?' and image_url is not distinct from '/assets/devices/mouse.webp');

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Chiqarish qurilmalari', 'easy', 'image_identification', 'Rasmdagi qurilmaning asosiy vazifasi nima?', '["Maʼlumotni uzoq muddat saqlash","Hujjatni skanerlash","Tasvir va matnni ekranda koʻrsatish","Ovozni yozib olish"]'::jsonb, '2'::jsonb, 'Monitor — kompyuter natijalarini ekranda koʻrsatadigan chiqarish qurilmasi.', 'U koʻrish uchun.', '/assets/devices/monitor.webp', 150, 25, 2
where not exists (select 1 from public.questions where question_text = 'Rasmdagi qurilmaning asosiy vazifasi nima?' and image_url is not distinct from '/assets/devices/monitor.webp');

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Chiqarish qurilmalari', 'medium', 'image_identification', 'Rasmda qanday qurilma tasvirlangan?', '["Server","Lazerli printer","Proyektor","Planshetli skaner"]'::jsonb, '1'::jsonb, 'Lazerli printer toner kukuni va lazer yordamida qogʻozga tez va sifatli chop etadi.', 'Undan qogʻoz chiqadi.', '/assets/devices/laser_printer.webp', 150, 25, 2
where not exists (select 1 from public.questions where question_text = 'Rasmda qanday qurilma tasvirlangan?' and image_url is not distinct from '/assets/devices/laser_printer.webp');

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kiritish qurilmalari', 'medium', 'image_identification', 'Rasmdagi qurilma nima uchun ishlatiladi?', '["Hujjatni qogʻozga chop etish","Qogʻozdagi hujjat va rasmlarni raqamli koʻrinishga oʻtkazish","Ovozni kuchaytirish","Tasvirni devorga tushirish"]'::jsonb, '1'::jsonb, 'Planshetli skaner qogʻoz hujjatni “suratga oladi” va kompyuterga raqamli tasvir sifatida kiritadi.', 'Hujjat shisha ustiga qoʻyiladi.', '/assets/devices/scanner.webp', 150, 25, 2
where not exists (select 1 from public.questions where question_text = 'Rasmdagi qurilma nima uchun ishlatiladi?' and image_url is not distinct from '/assets/devices/scanner.webp');

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kiritish qurilmalari', 'easy', 'image_identification', 'Rasmda qanday qurilma tasvirlangan?', '["Mikrofon","Shtrix-kod oʻquvchi","Veb-kamera","Proyektor"]'::jsonb, '2'::jsonb, 'Veb-kamera video qoʻngʻiroqlar va onlayn darslar uchun tasvirni kompyuterga kiritadi.', 'U odatda monitor ustiga oʻrnatiladi.', '/assets/devices/webcam.webp', 150, 25, 2
where not exists (select 1 from public.questions where question_text = 'Rasmda qanday qurilma tasvirlangan?' and image_url is not distinct from '/assets/devices/webcam.webp');

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kiritish qurilmalari', 'easy', 'image_identification', 'Rasmdagi qurilma kompyuterga nimani kiritadi?', '["Ovozni","Tasvirni","Matnni","Harakatni"]'::jsonb, '0'::jsonb, 'Mikrofon ovoz toʻlqinlarini elektr signaliga, soʻng raqamli maʼlumotga aylantiradi.', 'Unga gapiriladi.', '/assets/devices/microphone.webp', 150, 25, 2
where not exists (select 1 from public.questions where question_text = 'Rasmdagi qurilma kompyuterga nimani kiritadi?' and image_url is not distinct from '/assets/devices/microphone.webp');

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Chiqarish qurilmalari', 'easy', 'image_identification', 'Rasmdagi qurilmalar qaysi turkumga kiradi?', '["Saqlash qurilmalari","Chiqarish qurilmalari","Hisoblash qurilmalari","Kiritish qurilmalari"]'::jsonb, '1'::jsonb, 'Karnaylar kompyuterdagi raqamli ovozni eshitiladigan tovushga aylantiradi.', 'Ulardan musiqa eshitiladi.', '/assets/devices/speakers.webp', 150, 25, 2
where not exists (select 1 from public.questions where question_text = 'Rasmdagi qurilmalar qaysi turkumga kiradi?' and image_url is not distinct from '/assets/devices/speakers.webp');

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Chiqarish qurilmalari', 'easy', 'image_identification', 'Rasmdagi qurilma qanday vazifani bajaradi?', '["Tasvirni koʻrsatadi","Ovozni faqat foydalanuvchiga eshittiradi","Fayllarni saqlaydi","Ovozni kompyuterga kiritadi"]'::jsonb, '1'::jsonb, 'Quloqchinlar chiqarish qurilmasi: ovozni atrofdagilarni bezovta qilmasdan eshittiradi.', 'Ular quloqqa taqiladi.', '/assets/devices/headphones.webp', 150, 25, 2
where not exists (select 1 from public.questions where question_text = 'Rasmdagi qurilma qanday vazifani bajaradi?' and image_url is not distinct from '/assets/devices/headphones.webp');

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Saqlash qurilmalari va maʼlumot almashish', 'medium', 'image_identification', 'Rasmda ochiq holda koʻrsatilgan saqlash qurilmasi qaysi?', '["SSD","Operativ xotira (RAM)","Qattiq disk (HDD)","Optik diskovod"]'::jsonb, '2'::jsonb, 'HDD ichida aylanuvchi magnit plastina va oʻqish-yozish kallagi joylashgan qoʻl koʻrinadi.', 'Ichida yaltiroq aylanuvchi plastina bor.', '/assets/devices/hdd.webp', 150, 25, 2
where not exists (select 1 from public.questions where question_text = 'Rasmda ochiq holda koʻrsatilgan saqlash qurilmasi qaysi?' and image_url is not distinct from '/assets/devices/hdd.webp');

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Saqlash qurilmalari va maʼlumot almashish', 'hard', 'image_identification', 'Rasmdagi qurilma qaysi?', '["Videokarta","Tarmoq kartasi","Operativ xotira (RAM)","SSD (M.2 formatidagi)"]'::jsonb, '3'::jsonb, 'M.2 SSD — ona plataga toʻgʻridan-toʻgʻri ulanadigan ixcham va juda tez saqlash qurilmasi.', 'Bu qurilma fayllarni doimiy saqlaydi.', '/assets/devices/ssd.webp', 150, 25, 2
where not exists (select 1 from public.questions where question_text = 'Rasmdagi qurilma qaysi?' and image_url is not distinct from '/assets/devices/ssd.webp');

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Saqlash qurilmalari va maʼlumot almashish', 'easy', 'image_identification', 'Rasmda qanday qurilma tasvirlangan?', '["Bluetooth adapter","Zaryadlovchi kabel","Xotira kartasi (SD)","USB fleshka"]'::jsonb, '3'::jsonb, 'USB fleshka — flesh-xotiraga asoslangan koʻchma saqlash qurilmasi.', 'U USB portga ulanadi va fayllarni olib yurishga xizmat qiladi.', '/assets/devices/usb_flash.webp', 150, 25, 2
where not exists (select 1 from public.questions where question_text = 'Rasmda qanday qurilma tasvirlangan?' and image_url is not distinct from '/assets/devices/usb_flash.webp');

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Saqlash qurilmalari va maʼlumot almashish', 'easy', 'image_identification', 'Rasmdagi saqlash vositasi qaysi turga kiradi?', '["Qattiq jismli (flesh)","Optik","Bulutli","Magnit"]'::jsonb, '1'::jsonb, 'CD/DVD/Blu-ray — optik saqlash vositalari: ular lazer bilan oʻqiladi.', 'Uni lazer oʻqiydi.', '/assets/devices/dvd.webp', 150, 25, 2
where not exists (select 1 from public.questions where question_text = 'Rasmdagi saqlash vositasi qaysi turga kiradi?' and image_url is not distinct from '/assets/devices/dvd.webp');

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Saqlash qurilmalari va maʼlumot almashish', 'medium', 'image_identification', 'Rasmdagi qurilma koʻproq qayerda ishlatiladi?', '["Monitor sifatida","Kassada tovar skanerlashda","Printer kartriji sifatida","Fotoapparat va smartfonlarda"]'::jsonb, '3'::jsonb, 'Xotira kartasi (SD) — kichik flesh-xotira; fotoapparat, smartfon va dronlarda fayllarni saqlaydi.', 'U juda kichik va yassi.', '/assets/devices/sd_card.webp', 150, 25, 2
where not exists (select 1 from public.questions where question_text = 'Rasmdagi qurilma koʻproq qayerda ishlatiladi?' and image_url is not distinct from '/assets/devices/sd_card.webp');

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Maʼlumotlarni bevosita kiritish qurilmalari', 'easy', 'image_identification', 'Rasmda qanday qurilma tasvirlangan?', '["Sensorli qalam","Veb-kamera","Shtrix-kod oʻquvchi","Joystik"]'::jsonb, '2'::jsonb, 'Shtrix-kod oʻquvchi tovar kodini qizil nur yordamida oʻqiydi — bu bevosita maʼlumot kiritish.', 'Kassirlar undan foydalanadi.', '/assets/devices/barcode_scanner.webp', 150, 25, 2
where not exists (select 1 from public.questions where question_text = 'Rasmda qanday qurilma tasvirlangan?' and image_url is not distinct from '/assets/devices/barcode_scanner.webp');

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Chiqarish qurilmalari', 'medium', 'image_identification', 'Rasmdagi qurilmaning vazifasi nima?', '["Maʼlumotni saqlash","Hujjatlarni skanerlash","Ovozni yozib olish","Tasvirni katta ekranga yoki devorga tushirish"]'::jsonb, '3'::jsonb, 'Proyektor — kompyuter tasvirini katta ekranga chiqaradigan chiqarish qurilmasi.', 'Sinfda taqdimot koʻrsatish uchun ishlatiladi.', '/assets/devices/projector.webp', 150, 25, 2
where not exists (select 1 from public.questions where question_text = 'Rasmdagi qurilmaning vazifasi nima?' and image_url is not distinct from '/assets/devices/projector.webp');

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kiritish qurilmalari', 'medium', 'image_identification', 'Rasmda qanday qurilma tasvirlangan?', '["Joystik","Sichqoncha","Grafik planshet","Trekbol"]'::jsonb, '0'::jsonb, 'Joystik — dastak yordamida harakat yoʻnalishini kiritadigan qurilma; oʻyinlar va simulyatorlarda ishlatiladi.', 'Uchuvchilar simulyatorida shunga oʻxshash dastak bor.', '/assets/devices/joystick.webp', 150, 25, 2
where not exists (select 1 from public.questions where question_text = 'Rasmda qanday qurilma tasvirlangan?' and image_url is not distinct from '/assets/devices/joystick.webp');

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kiritish qurilmalari', 'medium', 'image_identification', 'Rasmda qanday qurilma tasvirlangan?', '["Skaner","Sensorli monitor","Klaviatura","Grafik planshet"]'::jsonb, '3'::jsonb, 'Grafik planshet maxsus qalam harakatini kompyuterga aniq uzatadi.', 'U qalam bilan birga keladi.', '/assets/devices/graphics_tablet.webp', 150, 25, 2
where not exists (select 1 from public.questions where question_text = 'Rasmda qanday qurilma tasvirlangan?' and image_url is not distinct from '/assets/devices/graphics_tablet.webp');

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kompyuter tizimining asosiy komponentlari', 'easy', 'single_choice', '1 bayt necha bitdan iborat?', '["16","8","10","4"]'::jsonb, '1'::jsonb, '1 bayt = 8 bit. Bit — eng kichik maʼlumot birligi (0 yoki 1).', 'Bu son 2 ning kubiga teng.', null, 200, 10, 3
where not exists (select 1 from public.questions where question_text = '1 bayt necha bitdan iborat?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Chiqarish qurilmalari', 'easy', 'single_choice', 'Qaysi biri chiqarish qurilmasi?', '["Karnay","Sichqoncha","Mikrofon","Skaner"]'::jsonb, '0'::jsonb, 'Karnay ovozni chiqaradi.', 'Undan musiqa eshitiladi.', null, 200, 10, 3
where not exists (select 1 from public.questions where question_text = 'Qaysi biri chiqarish qurilmasi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kiritish qurilmalari', 'easy', 'single_choice', 'Klaviatura qanday qurilma?', '["Kiritish qurilmasi","Saqlash qurilmasi","Chiqarish qurilmasi","Protsessor"]'::jsonb, '0'::jsonb, 'Klaviatura orqali matn va buyruqlar kiritiladi.', 'Biz unda yozamiz.', null, 200, 10, 3
where not exists (select 1 from public.questions where question_text = 'Klaviatura qanday qurilma?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kompyuter tizimining asosiy komponentlari', 'easy', 'single_choice', 'CPU qisqartmasi nimani bildiradi?', '["Kompyuter quvvat bloki","Rangli ekran","Markaziy protsessor","Markaziy printer"]'::jsonb, '2'::jsonb, 'CPU — Central Processing Unit, yaʼni markaziy protsessor.', 'C — Central.', null, 200, 10, 3
where not exists (select 1 from public.questions where question_text = 'CPU qisqartmasi nimani bildiradi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kompyuter tizimining asosiy komponentlari', 'easy', 'true_false', 'RAM — elektr oʻchganda ham maʼlumotni saqlaydigan doimiy xotira.', '["Toʻgʻri","Notoʻgʻri"]'::jsonb, '1'::jsonb, 'Notoʻgʻri. RAM energiyaga bogʻliq xotira: elektr oʻchsa, maʼlumot yoʻqoladi.', 'Saqlanmagan hujjat nima boʻladi?', null, 200, 10, 3
where not exists (select 1 from public.questions where question_text = 'RAM — elektr oʻchganda ham maʼlumotni saqlaydigan doimiy xotira.' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Operatsion tizimlar', 'easy', 'single_choice', 'Qaysi biri operatsion tizim EMAS?', '["Android","Windows","Microsoft Excel","Linux"]'::jsonb, '2'::jsonb, 'Excel — elektron jadval dasturi (amaliy dastur). Qolganlari operatsion tizimlar.', 'Bu dasturda jadvallar tuziladi.', null, 200, 10, 3
where not exists (select 1 from public.questions where question_text = 'Qaysi biri operatsion tizim EMAS?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Operatsion tizimlar', 'easy', 'single_choice', 'Android qaysi qurilmalar uchun mashhur operatsion tizim?', '["Fleshkalar","Smartfon va planshetlar","Printerlar","Faqat superkompyuterlar"]'::jsonb, '1'::jsonb, 'Android — mobil qurilmalar uchun eng keng tarqalgan operatsion tizimlardan biri.', 'Choʻntagingizdagi qurilmani eslang.', null, 200, 10, 3
where not exists (select 1 from public.questions where question_text = 'Android qaysi qurilmalar uchun mashhur operatsion tizim?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Saqlash qurilmalari va maʼlumot almashish', 'easy', 'single_choice', 'DVD qanday saqlash vositasi?', '["Optik","Magnit","Bulutli","Flesh"]'::jsonb, '0'::jsonb, 'DVD lazer nuri bilan oʻqiladi — u optik vosita.', 'Lazer!', null, 200, 10, 3
where not exists (select 1 from public.questions where question_text = 'DVD qanday saqlash vositasi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Chiqarish qurilmalari', 'easy', 'single_choice', 'Qaysi qurilma hujjatni qogʻozga chiqaradi?', '["Printer","Skaner","Monitor","Router"]'::jsonb, '0'::jsonb, 'Printer — qogʻozga chop etuvchi chiqarish qurilmasi.', 'Chop etish.', null, 200, 10, 3
where not exists (select 1 from public.questions where question_text = 'Qaysi qurilma hujjatni qogʻozga chiqaradi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kiritish qurilmalari', 'easy', 'true_false', 'Skaner — chiqarish qurilmasi.', '["Toʻgʻri","Notoʻgʻri"]'::jsonb, '1'::jsonb, 'Notoʻgʻri. Skaner qogʻozdagi maʼlumotni kompyuterga KIRITADI.', 'Maʼlumot qaysi tomonga harakatlanadi?', null, 200, 10, 3
where not exists (select 1 from public.questions where question_text = 'Skaner — chiqarish qurilmasi.' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kompyuter tizimining asosiy komponentlari', 'medium', 'single_choice', 'Maktab informatika kursida 1 KB necha baytga teng deb olinadi?', '["1024","512","8","100"]'::jsonb, '0'::jsonb, '1 KB = 1024 bayt (2¹⁰). Xalqaro SI tizimida 1 kB = 1000 bayt deb ham yoziladi.', 'Bu 2 ning 10-darajasi.', null, 200, 10, 3
where not exists (select 1 from public.questions where question_text = 'Maktab informatika kursida 1 KB necha baytga teng deb olinadi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kiritish qurilmalari', 'easy', 'single_choice', 'Qaysi qurilma ovozni kompyuterga kiritadi?', '["Mikrofon","Karnay","Monitor","Printer"]'::jsonb, '0'::jsonb, 'Mikrofon — ovozli kiritish qurilmasi.', 'Unga gapiriladi.', null, 200, 10, 3
where not exists (select 1 from public.questions where question_text = 'Qaysi qurilma ovozni kompyuterga kiritadi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kiritish qurilmalari', 'medium', 'single_choice', 'Smartfon ekrani telefon burilganda ham aylanishi uchun qaysi sensor ishlaydi?', '["Barmoq izi skaneri","Termometr","Akselerometr","Mikrofon"]'::jsonb, '2'::jsonb, 'Akselerometr qurilmaning holati va harakatini aniqlaydi.', 'U tezlanishni oʻlchaydi.', null, 200, 10, 3
where not exists (select 1 from public.questions where question_text = 'Smartfon ekrani telefon burilganda ham aylanishi uchun qaysi sensor ishlaydi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Saqlash qurilmalari va maʼlumot almashish', 'easy', 'single_choice', 'USB fleshka qanday xotira turiga asoslangan?', '["Flesh-xotira (qattiq jismli)","Magnit disk","Optik disk","Magnit lenta"]'::jsonb, '0'::jsonb, 'Fleshka — flesh-xotira mikrosxemasiga ega qattiq jismli qurilma.', 'Nomi oʻzida.', null, 200, 10, 3
where not exists (select 1 from public.questions where question_text = 'USB fleshka qanday xotira turiga asoslangan?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Saqlash qurilmalari va maʼlumot almashish', 'medium', 'single_choice', 'Bluetooth nima uchun ishlatiladi?', '["Qurilmalar orasida qisqa masofada simsiz maʼlumot almashish uchun","Uzoq masofaga elektr energiyasini uzatish uchun","Maʼlumotni magnit lentaga yozish uchun","Hujjatlarni chop etish uchun"]'::jsonb, '0'::jsonb, 'Bluetooth — qisqa masofali (odatda 10 m atrofida) simsiz aloqa texnologiyasi.', 'Simsiz quloqchinlar shu orqali ulanadi.', null, 200, 10, 3
where not exists (select 1 from public.questions where question_text = 'Bluetooth nima uchun ishlatiladi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kompyuter turlari', 'easy', 'single_choice', 'Qaysi qurilma eng koʻchma (mobil) hisoblanadi?', '["Server shkafi","Smartfon","Mainframe","Stol kompyuteri"]'::jsonb, '1'::jsonb, 'Smartfon choʻntakka sigʻadi va doimiy internetga ulanishi mumkin.', 'U choʻntakka sigʻadi.', null, 200, 10, 3
where not exists (select 1 from public.questions where question_text = 'Qaysi qurilma eng koʻchma (mobil) hisoblanadi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kompyuter tizimining asosiy komponentlari', 'medium', 'logical_puzzle', 'Ketma-ketlikni davom ettiring: 1, 2, 4, 8, 16, ?', '["64","20","24","32"]'::jsonb, '3'::jsonb, 'Har bir son oldingisidan 2 marta katta. Bu ikkilik sanoq tizimidagi razryad qiymatlari: 2⁰, 2¹, 2², …', 'Har safar ikkiga koʻpaytiring.', null, 250, 40, 4
where not exists (select 1 from public.questions where question_text = 'Ketma-ketlikni davom ettiring: 1, 2, 4, 8, 16, ?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kompyuter tizimining asosiy komponentlari', 'hard', 'short_answer', 'RAQAMLI QULF: Ikkilik sanoq tizimidagi 1010 sonini oʻnlik tizimga oʻtkazing. Natija — qulf kodi.', '[]'::jsonb, '["10"]'::jsonb, '1010₂ = 1·8 + 0·4 + 1·2 + 0·1 = 10.', 'Razryadlar qiymati chapdan oʻngga: 8, 4, 2, 1.', null, 250, 40, 4
where not exists (select 1 from public.questions where question_text = 'RAQAMLI QULF: Ikkilik sanoq tizimidagi 1010 sonini oʻnlik tizimga oʻtkazing. Natija — qulf kodi.' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kompyuter tizimining asosiy komponentlari', 'medium', 'short_answer', 'QULF KODI: 1 bayt = 8 bit. 4 bayt necha bitga teng? Javobni raqam bilan kiriting.', '[]'::jsonb, '["32"]'::jsonb, '4 × 8 = 32 bit.', '4 ni 8 ga koʻpaytiring.', null, 250, 40, 4
where not exists (select 1 from public.questions where question_text = 'QULF KODI: 1 bayt = 8 bit. 4 bayt necha bitga teng? Javobni raqam bilan kiriting.' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Chiqarish qurilmalari', 'medium', 'single_choice', 'NOSOZLIK: kompyuter yoqildi, ventilyator aylanyapti, lekin monitor qop-qora. Birinchi navbatda nimani tekshirish kerak?', '["Klaviatura tugmalarini","Internet tezligini","Monitor kabeli ulanganini va monitor yoqilganini","Printer siyohini"]'::jsonb, '2'::jsonb, 'Eng oddiy sabablardan boshlash kerak: monitor quvvati va video kabel ulanishi.', 'Eng oddiy sababdan boshlang.', null, 250, 40, 4
where not exists (select 1 from public.questions where question_text = 'NOSOZLIK: kompyuter yoqildi, ventilyator aylanyapti, lekin monitor qop-qora. Birinchi navbatda nimani tekshirish kerak?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Chiqarish qurilmalari', 'easy', 'single_choice', 'NOSOZLIK: printer “Qogʻoz tiqilib qoldi” xabarini bermoqda. Toʻgʻri harakat qaysi?', '["Kompyuterni formatlash","Printerni qattiq silkitish","Printerni oʻchirib, tiqilgan qogʻozni ehtiyotkorlik bilan chiqarish","Yangi monitor sotib olish"]'::jsonb, '2'::jsonb, 'Avval qurilmani xavfsiz holatga keltirib, qogʻozni yirtmasdan chiqarish kerak.', 'Xavfsizlik birinchi oʻrinda.', null, 250, 40, 4
where not exists (select 1 from public.questions where question_text = 'NOSOZLIK: printer “Qogʻoz tiqilib qoldi” xabarini bermoqda. Toʻgʻri harakat qaysi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kiritish qurilmalari', 'easy', 'single_choice', 'NOSOZLIK: sichqoncha kursori ekranda harakatlanmayapti. Eng oddiy birinchi qadam qaysi?', '["Monitorni oʻchirib qoʻyish","Sichqoncha ulanishini yoki batareyasini tekshirish","Protsessorni almashtirish","Operatsion tizimni qayta oʻrnatish"]'::jsonb, '1'::jsonb, 'Koʻp hollarda sabab oddiy: kabel chiqib qolgan yoki simsiz sichqoncha batareyasi tugagan.', 'Simsiz sichqonchaga nima kerak?', null, 250, 40, 4
where not exists (select 1 from public.questions where question_text = 'NOSOZLIK: sichqoncha kursori ekranda harakatlanmayapti. Eng oddiy birinchi qadam qaysi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Saqlash qurilmalarining afzallik va kamchiliklari', 'medium', 'single_choice', 'NOSOZLIK: noutbuk juda sekinlashgan, qattiq disk deyarli toʻlib qolgan. Eng toʻgʻri yechim qaysi?', '["Klaviaturani almashtirish","Wi-Fi ni oʻchirib qoʻyish","Ekran yorugʻligini oshirish","Keraksiz fayllarni oʻchirish yoki ularni tashqi/bulutli xotiraga koʻchirish"]'::jsonb, '3'::jsonb, 'Diskda boʻsh joy yetishmasa, tizim sekinlashadi. Joy boʻshatish yoki maʼlumotni boshqa xotiraga koʻchirish kerak.', 'Muammo xotirada.', null, 250, 40, 4
where not exists (select 1 from public.questions where question_text = 'NOSOZLIK: noutbuk juda sekinlashgan, qattiq disk deyarli toʻlib qolgan. Eng toʻgʻri yechim qaysi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kiritish qurilmalari', 'medium', 'logical_puzzle', 'MANTIQ: qurilma maʼlumotni kompyuterga KIRITADI va kompyuterdan CHIQARADI ham. Bu qaysi qurilma boʻlishi mumkin?', '["Sensorli ekran","Skaner","Klaviatura","Karnay"]'::jsonb, '0'::jsonb, 'Sensorli ekran teginishni qabul qiladi (kiritish) va tasvirni koʻrsatadi (chiqarish).', 'Smartfon ekranini eslang.', null, 250, 40, 4
where not exists (select 1 from public.questions where question_text = 'MANTIQ: qurilma maʼlumotni kompyuterga KIRITADI va kompyuterdan CHIQARADI ham. Bu qaysi qurilma boʻlishi mumkin?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kompyuter tizimining asosiy komponentlari', 'easy', 'true_false', 'Kompyuter oʻchganda ROMdagi maʼlumotlar yoʻqoladi.', '["Toʻgʻri","Notoʻgʻri"]'::jsonb, '1'::jsonb, 'Notoʻgʻri. ROM — doimiy xotira, undagi maʼlumot elektr oʻchganda ham saqlanadi.', 'ROM qanday xotira?', null, 250, 40, 4
where not exists (select 1 from public.questions where question_text = 'Kompyuter oʻchganda ROMdagi maʼlumotlar yoʻqoladi.' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Saqlash qurilmalarining afzallik va kamchiliklari', 'medium', 'true_false', 'HDD harakatlanuvchi mexanik qismlarga ega, shuning uchun u SSDga qaraganda zarbaga sezgirroq.', '["Toʻgʻri","Notoʻgʻri"]'::jsonb, '0'::jsonb, 'Toʻgʻri. Zarba paytida HDD kallagi aylanuvchi plastinaga tegib, uni shikastlashi mumkin.', 'Qaysi biri ichida aylanadi?', null, 250, 40, 4
where not exists (select 1 from public.questions where question_text = 'HDD harakatlanuvchi mexanik qismlarga ega, shuning uchun u SSDga qaraganda zarbaga sezgirroq.' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kiritish qurilmalari', 'medium', 'logical_puzzle', 'MANTIQ: qaysi qatordagi BARCHA qurilmalar kiritish qurilmalari?', '["Monitor, printer, karnay","Klaviatura, mikrofon, skaner","Mikrofon, karnay, proyektor","Klaviatura, monitor, printer"]'::jsonb, '1'::jsonb, 'Klaviatura, mikrofon va skaner maʼlumotni kompyuterga kiritadi.', 'Har bir qurilma kompyuterga nimadir “beradimi”?', null, 250, 40, 4
where not exists (select 1 from public.questions where question_text = 'MANTIQ: qaysi qatordagi BARCHA qurilmalar kiritish qurilmalari?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Saqlash qurilmalari va maʼlumot almashish', 'hard', 'logical_puzzle', 'MANTIQ: qaysi qatorda optik disklar sigʻimi KICHIKDAN KATTAGA toʻgʻri tartiblangan?', '["Blu-ray → DVD → CD","CD → DVD → Blu-ray","CD → Blu-ray → DVD","DVD → CD → Blu-ray"]'::jsonb, '1'::jsonb, 'CD ≈ 700 MB < DVD ≈ 4,7 GB < Blu-ray ≈ 25 GB.', 'Eng eskisi — eng kichigi.', null, 250, 40, 4
where not exists (select 1 from public.questions where question_text = 'MANTIQ: qaysi qatorda optik disklar sigʻimi KICHIKDAN KATTAGA toʻgʻri tartiblangan?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kompyuter tizimining asosiy komponentlari', 'medium', 'short_answer', 'QULF KODI: ketma-ketlikning keyingi sonini kiriting: 3, 6, 12, 24, ?', '[]'::jsonb, '["48"]'::jsonb, 'Har bir son oldingisidan 2 marta katta: 24 × 2 = 48.', 'Oldingi sonni ikkiga koʻpaytiring.', null, 250, 40, 4
where not exists (select 1 from public.questions where question_text = 'QULF KODI: ketma-ketlikning keyingi sonini kiriting: 3, 6, 12, 24, ?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Maʼlumotlarni bevosita kiritish qurilmalari', 'hard', 'short_answer', 'PAROL: bank cheklaridagi magnit siyohli raqamlarni oʻqiydigan texnologiyaning 4 harfli qisqartmasini yozing.', '[]'::jsonb, '["MICR"]'::jsonb, 'MICR — Magnetic Ink Character Recognition.', 'M… I… C… R…', null, 250, 40, 4
where not exists (select 1 from public.questions where question_text = 'PAROL: bank cheklaridagi magnit siyohli raqamlarni oʻqiydigan texnologiyaning 4 harfli qisqartmasini yozing.' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Maʼlumotlarni bevosita kiritish qurilmalari', 'hard', 'logical_puzzle', 'MANTIQ: kassir tovarni skanerlaydi, ekranda narx chiqadi va chek chop etiladi. Qurilmalar qaysi tartibda ishladi?', '["Ekran → shtrix-kod oʻquvchi → printer","Shtrix-kod oʻquvchi → protsessor → ekran va printer","Printer → protsessor → shtrix-kod oʻquvchi","Protsessor → printer → shtrix-kod oʻquvchi"]'::jsonb, '1'::jsonb, 'Kiritish (shtrix-kod) → qayta ishlash (protsessor narxni topadi) → chiqarish (ekran va chek printeri).', 'Kiritish → qayta ishlash → chiqarish.', null, 250, 40, 4
where not exists (select 1 from public.questions where question_text = 'MANTIQ: kassir tovarni skanerlaydi, ekranda narx chiqadi va chek chop etiladi. Qurilmalar qaysi tartibda ishladi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Maʼlumotlarni bevosita kiritish qurilmalari', 'medium', 'true_false', 'OCR texnologiyasi skanerlangan bosma matnni tahrirlanadigan matnga aylantira oladi.', '["Toʻgʻri","Notoʻgʻri"]'::jsonb, '0'::jsonb, 'Toʻgʻri. OCR tasvirdagi harflarni taniydi.', 'C — Character.', null, 250, 40, 4
where not exists (select 1 from public.questions where question_text = 'OCR texnologiyasi skanerlangan bosma matnni tahrirlanadigan matnga aylantira oladi.' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Saqlash qurilmalarining afzallik va kamchiliklari', 'hard', 'single_choice', 'Qaysi vaziyatda magnit lenta eng mos saqlash vositasi hisoblanadi?', '["Doʻstga bitta faylni tez uzatish","Kompyuter oʻyinlarini tez yuklash","Yirik tashkilotning har kungi toʻliq zaxira nusxasini arzon saqlash","Smartfonda tez-tez ochiladigan rasmlarni saqlash"]'::jsonb, '2'::jsonb, 'Lenta katta hajmni arzon saqlaydi, zaxira nusxadan esa kamdan-kam va ketma-ket foydalaniladi.', 'Zaxira nusxa (backup) haqida oʻylang.', null, 300, 45, 5
where not exists (select 1 from public.questions where question_text = 'Qaysi vaziyatda magnit lenta eng mos saqlash vositasi hisoblanadi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kompyuter tizimining asosiy komponentlari', 'hard', 'single_choice', 'Nima uchun kompyuterni yuklovchi dastur RAMda emas, balki ROMda saqlanadi?', '["Chunki u elektr oʻchganda ham yoʻqolmasligi kerak","Chunki ROMga foydalanuvchi oʻyinlarini yozadi","Chunki RAM juda sekin ishlaydi","Chunki RAM faqat rasmlarni saqlaydi"]'::jsonb, '0'::jsonb, 'Kompyuter yoqilishi bilan ishga tushirish dasturi tayyor turishi kerak — buni faqat doimiy xotira (ROM) taʼminlaydi.', 'RAM va ROMning asosiy farqi nimada?', null, 300, 45, 5
where not exists (select 1 from public.questions where question_text = 'Nima uchun kompyuterni yuklovchi dastur RAMda emas, balki ROMda saqlanadi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Maʼlumotlarni bevosita kiritish qurilmalari', 'hard', 'single_choice', 'Kutubxona javondagi kitoblarni har birini qoʻlga olmasdan, masofadan hisobga olmoqchi. Qaysi texnologiya eng mos?', '["OMR","MICR","RFID","Shtrix-kod"]'::jsonb, '2'::jsonb, 'RFID yorliqlari radiotoʻlqin orqali oʻqiladi va toʻgʻridan-toʻgʻri koʻrinishni talab qilmaydi; bir vaqtda koʻp yorliqni oʻqish mumkin.', 'Bu texnologiya radiotoʻlqindan foydalanadi.', null, 300, 45, 5
where not exists (select 1 from public.questions where question_text = 'Kutubxona javondagi kitoblarni har birini qoʻlga olmasdan, masofadan hisobga olmoqchi. Qaysi texnologiya eng mos?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kompyuter turlari', 'hard', 'single_choice', 'Ilmiy markaz har kuni ulkan hajmdagi ob-havo maʼlumotlarini juda tez hisoblashi kerak. Qaysi kompyuter turi eng mos?', '["Smart soat","Superkompyuter","Planshet","Noutbuk"]'::jsonb, '1'::jsonb, 'Superkompyuterlar soniyasiga trillionlab amal bajaradi va ob-havo modellashtirishda ishlatiladi.', 'Eng kuchli kompyuter turi.', null, 300, 45, 5
where not exists (select 1 from public.questions where question_text = 'Ilmiy markaz har kuni ulkan hajmdagi ob-havo maʼlumotlarini juda tez hisoblashi kerak. Qaysi kompyuter turi eng mos?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kiritish qurilmalari', 'hard', 'single_choice', 'Shifoxonada bemorning yurak urishi doimiy kuzatiladi va xavfli holatda signal chalinadi. Bu tizimda qaysi qurilmalar ishlaydi?', '["Faqat klaviatura","Faqat printer","Sensor (kiritish) hamda ekran va signal (chiqarish)","Faqat DVD disk"]'::jsonb, '2'::jsonb, 'Sensor maʼlumotni uzluksiz kiritadi, kompyuter uni tahlil qiladi, ekran va signal esa natijani chiqaradi.', 'Kiritish → qayta ishlash → chiqarish.', null, 300, 45, 5
where not exists (select 1 from public.questions where question_text = 'Shifoxonada bemorning yurak urishi doimiy kuzatiladi va xavfli holatda signal chalinadi. Bu tizimda qaysi qurilmalar ishlaydi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Yangi texnologiyalarning taʼsiri', 'medium', 'single_choice', 'Sunʼiy intellekt keng qoʻllanilishining salbiy taʼsirlaridan biri qaysi?', '["Internetning yoʻqolib ketishi","Baʼzi kasblarda ish oʻrinlarining qisqarishi","Kompyuterlarning butunlay ishlamay qolishi","Elektr energiyasining bepul boʻlib qolishi"]'::jsonb, '1'::jsonb, 'Avtomatlashtirish takroriy ishlarda inson mehnatiga ehtiyojni kamaytiradi, ammo yangi kasblar ham paydo boʻladi.', 'Mehnat bozori haqida oʻylang.', null, 300, 45, 5
where not exists (select 1 from public.questions where question_text = 'Sunʼiy intellekt keng qoʻllanilishining salbiy taʼsirlaridan biri qaysi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Saqlash qurilmalarining afzallik va kamchiliklari', 'hard', 'single_choice', 'Fotograf 200 GB fotosuratni mijozga tez yetkazmoqchi, lekin internet juda sekin. Eng qulay yechim qaysi?', '["Tashqi SSD yoki katta sigʻimli fleshka","300 ta CD disk","Magnit lenta","Har bir rasmni elektron pochtada alohida yuborish"]'::jsonb, '0'::jsonb, 'Koʻchma SSD/fleshka katta hajmni tez yozadi va oʻqiydi, internetga bogʻliq emas.', 'Tezkor va koʻchma xotira kerak.', null, 300, 45, 5
where not exists (select 1 from public.questions where question_text = 'Fotograf 200 GB fotosuratni mijozga tez yetkazmoqchi, lekin internet juda sekin. Eng qulay yechim qaysi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Operatsion tizimlar', 'hard', 'single_choice', 'Koʻrish qobiliyati cheklangan foydalanuvchi uchun qaysi interfeys eng qulay boʻlishi mumkin?', '["Faqat sichqoncha bilan boshqaruv","Faqat mayda shriftli buyruqlar satri","Ovozli boshqaruv interfeysi","Faqat kichik ikonkali grafik menyu"]'::jsonb, '2'::jsonb, 'Ovozli interfeys ekranga qaramasdan buyruq berish va javobni eshitish imkonini beradi.', 'Koʻz oʻrniga qaysi sezgi ishlatiladi?', null, 300, 45, 5
where not exists (select 1 from public.questions where question_text = 'Koʻrish qobiliyati cheklangan foydalanuvchi uchun qaysi interfeys eng qulay boʻlishi mumkin?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kompyuter tizimining asosiy komponentlari', 'hard', 'short_answer', 'BOSS QULFI: ikkilik sanoq tizimidagi 1111 sonini oʻnlik tizimga oʻtkazing.', '[]'::jsonb, '["15"]'::jsonb, '1111₂ = 8 + 4 + 2 + 1 = 15.', 'Razryadlar qiymati: 8, 4, 2, 1.', null, 300, 45, 5
where not exists (select 1 from public.questions where question_text = 'BOSS QULFI: ikkilik sanoq tizimidagi 1111 sonini oʻnlik tizimga oʻtkazing.' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Saqlash qurilmalarining afzallik va kamchiliklari', 'hard', 'single_choice', 'Nima uchun planshetlarda HDD emas, balki flesh-xotira ishlatiladi?', '["U yengil, kam energiya sarflaydi va zarbaga chidamli","U har doim HDDdan arzonroq","U magnit maydonida yaxshiroq ishlaydi","Unga faqat bir marta yozish mumkin"]'::jsonb, '0'::jsonb, 'Mobil qurilmalarda vazn, batareya sarfi va chidamlilik muhim — flesh-xotira bularning barchasida ustun.', 'Planshet tushib ketsa nima boʻladi?', null, 300, 45, 5
where not exists (select 1 from public.questions where question_text = 'Nima uchun planshetlarda HDD emas, balki flesh-xotira ishlatiladi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Operatsion tizimlar', 'hard', 'logical_puzzle', 'Operatsion tizimning qaysi funksiyasi bir vaqtda bir nechta dastur ishlashini taʼminlaydi?', '["Faqat fayllarni oʻchirish","Printerga siyoh qoʻshish","Ekran yorugʻligini oshirish","Jarayonlar va xotirani boshqarish (koʻp vazifalilik)"]'::jsonb, '3'::jsonb, 'OT protsessor vaqtini va xotirani dasturlar orasida taqsimlaydi — bu multitasking.', 'Musiqa tinglab, bir vaqtda matn yozish.', null, 300, 45, 5
where not exists (select 1 from public.questions where question_text = 'Operatsion tizimning qaysi funksiyasi bir vaqtda bir nechta dastur ishlashini taʼminlaydi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Yangi texnologiyalarning taʼsiri', 'medium', 'single_choice', 'Qaysi texnologiya ishlab chiqarishda ham, tibbiyotda ham (masalan, protez yasashda) katta oʻzgarish yasadi?', '["Elektron-nurli (CRT) monitor","Disketa","3D chop etish","Matritsali printer"]'::jsonb, '2'::jsonb, '3D printerlar shaxsga moslashtirilgan protezlar, ehtiyot qismlar va prototiplarni tez yasash imkonini beradi.', 'U qatlamma-qatlam “quradi”.', null, 300, 45, 5
where not exists (select 1 from public.questions where question_text = 'Qaysi texnologiya ishlab chiqarishda ham, tibbiyotda ham (masalan, protez yasashda) katta oʻzgarish yasadi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kiritish qurilmalari', 'medium', 'matching', 'MOSLASHTIRISH: Qurilmalarni vazifasiga moslang.', '["Klaviatura","Printer","Fleshka","Mikrofon"]'::jsonb, '["Kiritish","Chiqarish","Saqlash","Kiritish"]'::jsonb, 'Kiritish qurilmalari maʼlumotni kompyuterga kiritadi, chiqarish qurilmalari natijani koʻrsatadi, saqlash qurilmalari maʼlumotni uzoq saqlaydi.', 'Maʼlumot qaysi tomonga harakatlanadi?', null, 250, 40, 4
where not exists (select 1 from public.questions where question_text = 'MOSLASHTIRISH: Qurilmalarni vazifasiga moslang.' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Saqlash qurilmalari va maʼlumot almashish', 'medium', 'matching', 'MOSLASHTIRISH: Saqlash qurilmalarini ishlash usuliga moslang.', '["Qattiq disk (HDD)","DVD disk","SSD","Magnit lenta"]'::jsonb, '["Magnit","Optik (lazer)","Flesh-xotira","Magnit"]'::jsonb, 'HDD va lenta maʼlumotni magnitlangan sirtga yozadi, CD/DVD lazer nuri bilan oʻqiladi, SSD va fleshka esa harakatlanuvchi qismlarsiz flesh-xotiradan foydalanadi.', 'Magnit, lazer yoki mikrosxema?', null, 250, 40, 4
where not exists (select 1 from public.questions where question_text = 'MOSLASHTIRISH: Saqlash qurilmalarini ishlash usuliga moslang.' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kompyuter qurilmalari va dasturiy taʼminot', 'medium', 'matching', 'MOSLASHTIRISH: Dasturlarni turiga moslang.', '["Windows","Matn muharriri","Antivirus","Linux"]'::jsonb, '["Operatsion tizim","Amaliy dastur","Utilita (xizmat dasturi)","Operatsion tizim"]'::jsonb, 'Operatsion tizim kompyuterni boshqaradi, amaliy dasturlar foydalanuvchi vazifasini bajaradi, utilitalar esa tizimga xizmat koʻrsatadi (himoya, tozalash, arxivlash).', 'Kim kompyuterni boshqaradi, kim foydalanuvchiga xizmat qiladi?', null, 250, 40, 4
where not exists (select 1 from public.questions where question_text = 'MOSLASHTIRISH: Dasturlarni turiga moslang.' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Maʼlumotlarni bevosita kiritish qurilmalari', 'hard', 'matching', 'MOSLASHTIRISH: Bevosita kiritish usullarini qoʻllanish joyiga moslang.', '["Shtrix-kod skaneri","OMR","RFID","Chip va PIN"]'::jsonb, '["Doʻkon kassasi","Test varaqalarini tekshirish","Kontaktsiz kirish kartasi","Bank kartasi bilan toʻlov"]'::jsonb, 'Bevosita kiritish qurilmalari maʼlumotni klaviaturasiz, tez va xatosiz kiritadi: shtrix-kod — tovarlar, OMR — belgilangan javoblar, RFID — radio metkalar, chip va PIN — bank kartasi.', 'Har bir texnologiya qayerda koʻp uchraydi?', null, 250, 40, 4
where not exists (select 1 from public.questions where question_text = 'MOSLASHTIRISH: Bevosita kiritish usullarini qoʻllanish joyiga moslang.' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Kompyuter turlari', 'medium', 'matching', 'MOSLASHTIRISH: Kompyuter turlarini tavsifiga moslang.', '["Mainframe","Noutbuk","Smartfon","Stol kompyuteri"]'::jsonb, '["Minglab foydalanuvchiga xizmat qiluvchi kuchli kompyuter","Batareyali koʻchma kompyuter","Choʻntakdagi mobil qurilma","Doimiy joyda turadigan shaxsiy kompyuter"]'::jsonb, 'Kompyuterlar oʻlchami, quvvati va koʻchmaligi boʻyicha farq qiladi.', 'Eng kattasi va eng kichigini toping.', null, 250, 40, 4
where not exists (select 1 from public.questions where question_text = 'MOSLASHTIRISH: Kompyuter turlarini tavsifiga moslang.' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Chiqarish qurilmalari', 'medium', 'multi_step', 'NOSOZLIK ZANJIRI: Printer hujjatni chop etmayapti. Muammoni bosqichma-bosqich toping.', '[{"text":"Avval nimani tekshirasiz?","options":["Printer yoqilgan va kompyuterga ulanganini","Monitor yorugʻligini","Kompyuter protsessorini"]},{"text":"Printer yoqilgan va ulangan, lekin ekranda “Qogʻoz tugadi” xabari chiqdi. Nima qilasiz?","options":["Klaviaturani almashtiraman","Operatsion tizimni qayta oʻrnataman","Lotokka qogʻoz solaman"]},{"text":"Qogʻoz solindi, lekin sahifa juda xira chiqyapti. Ehtimoliy sabab?","options":["Sichqoncha buzilgan","Siyoh yoki toner tugayapti","Internet sekin"]}]'::jsonb, '[0,2,1]'::jsonb, 'Nosozlik eng oddiy sabablardan boshlab tekshiriladi: quvvat va ulanish → qogʻoz → siyoh yoki toner.', 'Oddiydan murakkabga.', null, 250, 40, 4
where not exists (select 1 from public.questions where question_text = 'NOSOZLIK ZANJIRI: Printer hujjatni chop etmayapti. Muammoni bosqichma-bosqich toping.' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Saqlash qurilmalari va maʼlumot almashish', 'hard', 'multi_step', 'RAQAMLI ZANJIR: Hajmi 2 GB boʻlgan videoni 8 GB lik fleshkaga yozmoqchisiz. Hisobni qadamma-qadam bajaring.', '[{"text":"1 GB necha MB ga teng?","options":["1000 KB","8 MB","1024 MB","100 MB"]},{"text":"Demak, 2 GB lik video necha MB?","options":["4096 MB","2048 MB","1024 MB","2000 KB"]},{"text":"8 GB lik fleshkaga shunday videolardan nechtasi sigʻadi?","options":["2 ta","16 ta","8 ta","4 ta"]}]'::jsonb, '[2,1,3]'::jsonb, '1 GB = 1024 MB, shuning uchun 2 GB = 2048 MB. 8 GB ÷ 2 GB = 4 ta video.', 'Har bir birlik oldingisidan 1024 marta katta.', null, 250, 40, 4
where not exists (select 1 from public.questions where question_text = 'RAQAMLI ZANJIR: Hajmi 2 GB boʻlgan videoni 8 GB lik fleshkaga yozmoqchisiz. Hisobni qadamma-qadam bajaring.' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Operatsion tizimlar', 'hard', 'multi_step', 'BOSS ZANJIRI: Kompyuter yoqilgandan to dastur ishga tushguncha nima sodir boʻladi?', '[{"text":"Kompyuter yoqilganda birinchi boʻlib nima ishga tushadi?","options":["Brauzer","BIOS/UEFI — qurilmalarni tekshiradi","Matn muharriri"]},{"text":"Shundan keyin qaysi dastur xotiraga yuklanadi?","options":["Antivirus bazasi","Fotosuratlar papkasi","Operatsion tizim"]},{"text":"Foydalanuvchi dastur belgisini bosganda uni nima ishga tushiradi?","options":["Sichqoncha","Operatsion tizim — dasturni xotiraga yuklaydi","Monitor"]}]'::jsonb, '[1,2,1]'::jsonb, 'Yuklanish ketma-ketligi: BIOS/UEFI qurilmalarni tekshiradi → operatsion tizim yuklanadi → OT foydalanuvchi dasturlarini xotiraga yuklab ishga tushiradi.', 'Avval apparat, keyin OT, keyin dasturlar.', null, 300, 45, 5
where not exists (select 1 from public.questions where question_text = 'BOSS ZANJIRI: Kompyuter yoqilgandan to dastur ishga tushguncha nima sodir boʻladi?' and image_url is not distinct from null);

insert into public.questions (subject, grade, category, difficulty, question_type, question_text, options, correct_answer, explanation, hint, image_url, default_points, default_time_limit, recommended_round)
select 'Informatika', 9, 'Maʼlumotlarni bevosita kiritish qurilmalari', 'hard', 'multi_step', 'BOSS ZANJIRI: Xaridor doʻkonda tovar sotib olmoqda. Maʼlumot qanday harakatlanishini kuzating.', '[{"text":"Kassir tovarni qanday tez kiritadi?","options":["Nomini klaviaturada yozadi","Shtrix-kodni skaner bilan oʻqiydi","Mikrofonga aytadi"]},{"text":"Tovar narxi qayerdan olinadi?","options":["Xaridorning telefonidan","Printer xotirasidan","Doʻkonning maʼlumotlar bazasidan"]},{"text":"Xaridor bank kartasi bilan toʻlaydi. Karta maʼlumoti qanday oʻqiladi?","options":["Chip va PIN yoki kontaktsiz (NFC) terminal orqali","Kassir qoʻlda yozib","Skaner bilan rasmga olib"]}]'::jsonb, '[1,2,0]'::jsonb, 'Doʻkonda maʼlumot avtomatik kiritiladi: shtrix-kod → maʼlumotlar bazasidan narx → chip va PIN yoki NFC orqali toʻlov.', 'Har qadamda eng tez va xatosiz usulni tanlang.', null, 300, 45, 5
where not exists (select 1 from public.questions where question_text = 'BOSS ZANJIRI: Xaridor doʻkonda tovar sotib olmoqda. Maʼlumot qanday harakatlanishini kuzating.' and image_url is not distinct from null);
